import os
import json
from typing import Any, Dict, List, Optional
from anthropic import Anthropic

PROMPT_VERSION = "v1"


def _client() -> Anthropic:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError("ANTHROPIC_API_KEY is not set")
    return Anthropic(api_key=key)


def build_metadata_prompt(
    allowed_colors: List[str],
    allowed_designs: List[str],
    allowed_themes: List[str],
    feedback_examples: Optional[List[Dict[str, Any]]] = None,
) -> str:
    examples_text = ""
    if feedback_examples:
        # keep it short (token/cost friendly)
        lines = []
        for i, ex in enumerate(feedback_examples[:5], start=1):
            lines.append(
                f"Example {i}:\n"
                f"- Original: {json.dumps(ex.get('original_metadata', {}))}\n"
                f"- Corrected: {json.dumps(ex.get('corrected_metadata', {}))}\n"
                f"- Notes: {ex.get('correction_notes', '')}\n"
            )
        examples_text = "\nPAST CORRECTIONS (use these as guidance):\n" + "\n".join(lines)

    return f"""
You are a precise cataloging assistant for wallpaper swatches.

You MUST output ONLY valid JSON (no markdown, no extra text) with this schema:
{{
  "primary_color": "string",
  "secondary_colors": ["string", "..."],
  "design_style": "string",
  "theme": "string",
  "suitable_for": "string"
}}

CONSTRAINTS:
- primary_color MUST be exactly one item from ALLOWED_COLORS.
- secondary_colors MUST be a list of 0+ items from ALLOWED_COLORS (no duplicates).
- design_style MUST be exactly one item from ALLOWED_DESIGNS.
- theme MUST be exactly one item from ALLOWED_THEMES.
- suitable_for is FREE TEXT (short phrase), generated by you.

ALLOWED_COLORS: {allowed_colors}
ALLOWED_DESIGNS: {allowed_designs}
ALLOWED_THEMES: {allowed_themes}

{examples_text}

Return only JSON.
""".strip()


def build_description_prompt(accepted: Dict[str, Any]) -> str:
    # Must include primary_color, secondary_colors, design_style, theme (not focus on suitable_for)
    primary = accepted.get("primary_color", "")
    secondary = accepted.get("secondary_colors", [])
    design = accepted.get("design_style", "")
    theme = accepted.get("theme", "")

    return f"""
Write ONE short but detailed physical description (60–120 words) of the wallpaper swatch.

HARD REQUIREMENTS:
- You MUST explicitly mention these accepted metadata values:
  - Primary color: "{primary}"
  - Secondary colors: {secondary}
  - Design style: "{design}"
  - Theme: "{theme}"
- Do NOT focus on "suitable_for" and do NOT mention it unless absolutely necessary.
- You MAY add other physically descriptive attributes useful for similarity & trend analysis:
  pattern/motif type, scale, density, contrast, line quality, texture cues (matte/gloss/emboss-like), repetition regularity.

Output only the paragraph, no bullets, no headings.
""".strip()


def claude_extract_metadata(image_b64: str, media_type: str, prompt: str) -> Dict[str, Any]:
    """
    media_type examples: "image/jpeg", "image/png", "image/webp"
    """
    c = _client()
    resp = c.messages.create(
        model="claude-sonnet-4-20250514",  # Updated to current model
        max_tokens=600,
        temperature=0.2,
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "image", "source": {"type": "base64", "media_type": media_type, "data": image_b64}},
                    {"type": "text", "text": prompt},
                ],
            }
        ],
    )
    text = resp.content[0].text  # Anthropic returns list of content blocks
    return json.loads(text)


def claude_generate_description(image_b64: str, media_type: str, prompt: str) -> str:
    c = _client()
    resp = c.messages.create(
        model="claude-sonnet-4-20250514",  # Updated to current model
        max_tokens=350,
        temperature=0.3,
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "image", "source": {"type": "base64", "media_type": media_type, "data": image_b64}},
                    {"type": "text", "text": prompt},
                ],
            }
        ],
    )
    return resp.content[0].text.strip()