ANTHROPIC_API_KEY=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
DATABASE_URL=postgresql://neondb_owner:npg_wFEaZmeQhL14@ep-winter-truth-a1hjoz0q-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
